### ISSUE TITLE
Not working with Ansible AWX

### ISSUE THREAD

**Issue by metabsd** [ServiceNowITOM/ansible-sn-inventory#10]
Hi,

I just try your script with AWX. The script need a python library not include in AWX (Upstream version of Ansible Tower). That version plan to give the possibility to user Ansible Tower as a container. I speak with agaffney on ansible-awx (freenode).

The error message

```
2018-04-26 15:54:36,602 INFO awx.main.commands.inventory_import Updating inventory 3: ServiceNow 2018-04-26 15:54:36,646 DEBUG awx.main.commands.inventory_import Using system install of ansible-inventory CLI: /usr/bin/ansible-inventory 2018-04-26 15:54:36,646 INFO awx.main.commands.inventory_import Reading Ansible inventory source: /tmp/awx_inventory_um4uIV/tmpfztbih Traceback (most recent call last): File "/usr/bin/awx-manage", line 9, in <module> load_entry_point('awx==1.0.5.31', 'console_scripts', 'awx-manage')() File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage execute_from_command_line(sys.argv) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line utility.execute() File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute self.fetch_command(subcommand).run_from_argv(self.argv) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv self.execute(*args, **cmd_options) File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute output = self.handle(*args, **options) File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 993, in handle self.is_custom) File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 242, in load_inventory_source is_custom=is_custom).load() File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 177, in load data = self.command_to_json(base_args + ['--list']) File "/usr/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 160, in command_to_json self.method, proc.returncode, stdout, stderr)) RuntimeError: ansible-inventory failed (rc=1) with stdout: stderr:  [WARNING]:  * Failed to parse /tmp/awx_inventory_um4uIV/tmpfztbih with script plugin: Inventory script (/tmp/awx_inventory_um4uIV/tmpfztbih) had an execution error: Traceback (most recent call last):   File "/tmp/awx_inventory_um4uIV/tmpfztbih", line 41, in <module>     import configparser ImportError: No module named configparser  [WARNING]: Unable to parse /tmp/awx_inventory_um4uIV/tmpfztbih as an inventory source ERROR! No inventory was parsed, please check your configuration and options.
```

The comment on ansible-awx channel.

> <agaffney> Andrew Gaffney the ec2.py inventory script seems to use `from six.moves import configparser

> <agaffney> Andrew Gaffney metabsd: `import configparser` is not the same as `from six.moves import configparser

Do you think if it's possible your you to adapt the script to be compatible with AWX without using a custom image of AWX please ??

Thx a lot!!!

**Comment by metabsd** [comment]
I just try it and change `import configparser` for `from six.moves import configparser` and it's working fine. Would be great if you choose to switch. Tomorow I will try it in AWX. Thank you!

**Comment by ursetto** [comment]
I opened PR https://github.com/ServiceNowITOM/ansible-sn-inventory/pull/11 to use the six aliasing mechanism, after verifying it works and seems like the best solution.
