### ISSUE TITLE
Using now.py with cache option.

### ISSUE THREAD

**Issue by metabsd** [ServiceNowITOM/ansible-sn-inventory#4]
First time I use now.py it's working but second time I got that error about the cache.

```
./now.py
Traceback (most recent call last):
  File "./now.py", line 274, in <module>
    main(sys.argv)
  File "./now.py", line 269, in main
    inventory.generate()
  File "./now.py", line 179, in generate
    content = self._invoke('GET', path, None)
  File "./now.py", line 122, in _invoke
    inventory = self._get_cache(cache_name, None)
  File "./now.py", line 103, in _get_cache
    cache_max_age = int(os.environ.get('SN_CACHE_MAX_AGE'))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

That my option in now.ini about cache.

```
[defaults]

# Specify the number of seconds to use the inventory cache before it is
# considered stale.  If not defined, defaults to 0 seconds.
cache_max_age = 3600

# Specify the directory used for storing the inventory cache.  If not defined,
# caching will be disabled.
cache_dir = .cache/ansible
```

By the way great work.

**Comment by amittell** [comment]
Fixed int() error for unset env variable in commit f11ba83585dca526862d3695f9982b22a6076dba, let me know if you have any more problems.
