### ISSUE TITLE
Try to use groups with now.ini

### ISSUE THREAD

**Issue by metabsd** [ServiceNowITOM/ansible-sn-inventory#6]
I try to use that config.

```
[config]

# Comma seperated string providing additional table columns to use as groups. Groups can overlap with fields.

groups = 'used_for'

# Comma seperated string providing additional table columns to add as host vars to each inventory host.

#fields = 'company, os, os_version'

```

I got that error

```
./now.py 
Traceback (most recent call last):
  File "./now.py", line 274, in <module>
    main(sys.argv)
  File "./now.py", line 269, in main
    inventory.generate()
  File "./now.py", line 172, in generate
    set(base_fields + base_groups + self.fields + self.groups))
TypeError: can only concatenate list (not "unicode") to list
```

**Comment by amittell** [comment]
Resolve in d352b270ae9a9aa53e0a0c62d36da5e10419de96

**Comment by amittell** [comment]
Please note, don’t use quotes around groups or fields. Update the example config to show the correct syntax.
